name: docker-learning-example

services:
  frontend:
    build:
      context: src/frontend
    container_name: nginx
    ports:
      - 80:80

  fastapi:
    build:
      context: src/backend/api
    container_name: fastapi
