name: my-app

services:
  frontend:
    build:
      context: src/frontend
    container_name: nginx-frontend
    ports:
      - 80:80

  fastapi:
    build:
      context: src/backend/api
    container_name: fastapi
    ports:
      - 81:8000
